#!/bin/sh
# chkconfig: 2345 10 90
# description: Start and Stop redis

PATH=/usr/local/bin:/sbin:/usr/bin:/bin

REDIS_PORT=6379 #实际环境而定
REDIS_SERVER=/usr/local/bin/redis-server  #实际环境而定
REDIS_CLI=/usr/local/bin/redis-cli #实际环境而定

PID_FILE=/var/run/redis.pid
CONF="/etc/redis.conf" #实际环境而定

case "$1" in
        start)
                if [ -f $PID_FILE ]
                then
                        echo "$PID_FILE exists, process is already running or crashed."
                else
                        echo "Starting Redis server..."
                        $REDIS_SERVER $CONF
                fi
                if [ "$?"="0" ]
                then
                        echo "Redis is running..."
                fi
                ;;
        stop)
                if [ ! -f $PID_FILE ]
                then
                        echo "$PID_FILE exists, process is not running."
                else
                        PID=$(cat $PID_FILE)
                        echo "Stopping..."
                        $REDIS_CLI -p $REDIS_PORT SHUTDOWN
                        while [ -x $PID_FILE ]
                        do
                                echo "Waiting for Redis to shutdown..."
                                sleep 1
                        done
                        echo "Redis stopped"
                fi
                ;;
        restart|force-reload)
                ${0} stop
                ${0} start
                ;;
        *)
                echo "Usage: /etc/init.d/redis {start|stop|restart|force-reload}" >&2
                exit 1
esac